### ISSUE TITLE
:sparkles: Create company form

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/Brainstorming.2023#1]
# Description
Some description.

# Tasks
- [ ] A small task
- [ ] Another small task

# Acceptance Criteria
- [ ] Can add company
- [ ] Can edit company
- [ ] Can delete company
